services:
  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - djangonetwork

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '3988'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - djangonetwork

volumes:
  pg_data:

networks:
  djangonetwork:

#    networks:
#      - djangonetwork
#
#  redis:
#    restart: always
#    image: redis
#    networks:
#      - djangonetwork
#
#  # rabbitmq:
#  #   restart: always
#  #   image: rabbitmq:3-management
#  #   ports:
#  #     - ${RABBITMQ_PORT:-15672}:15672
#  #   environment:
#  #     - RABBITMQ_DEFAULT_PASS=2309
#  #     - RABBITMQ_DEFAULT_VHOST=vhost
#  #   volumes:
#  #     - rabbitmq:/var/lib/rabbitmq
#  #   networks:
#  #     - djangonetwork
#
#networks:
#  djangonetwork:
#    driver: bridge
#
#volumes:
#  pg_data: null
#  rabbitmq: null
