# Generated by Django 5.1.6 on 2025-02-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_waiter_last_login_alter_waiter_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
